#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"
alias c="clear"

du="Do not use non git aliases for git"

# Git - due for deprecation
alias g="echo $du"
alias gs="echo $du"
alias gc="echo $du"
alias gp="echo $du"
alias ga="echo $du"

# Pipe diff of last commit into vim

alias gd="git diff HEAD | view -"

# Weird Time Thing
alias showtime="while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &"

# EVN
alias dev="export NODE_ENV=development"
alias prod="export NODE_ENV=production"
alias stage="export NODE_ENV=staging"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="clear && pwd && ls -FGl"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Forward traffic out to the network
alias gotoforwardmode="sudo sysctl -w net.inet.ip.forwarding=1"
alias exitforwardmode="sudo sysctl -w net.inet.ip.forwarding=0"

# Syntax highlighting for making keynotes
alias hit="pbpaste | highlight --syntax=js --style=seashell --line-numbers -O rtf | pbcopy"
alias hithtml="pbpaste | highlight --syntax=html --style=seashell --line-numbers -O rtf | pbcopy"
alias _hit="highlight --syntax=js --style=seashell --line-numbers -O rtf | pbcopy"

# Open a new instance of slack so you can have two windows open simutaneously
alias slack="open -n /Applications/Slack.app/"

# Print out ipaddress for much info
alias ip="ifconfig | grep \"inet \""
